### ISSUE TITLE
 Call to undefined method ……Providers\Log\Logger::channel() 

### ISSUE THREAD

**Issue by kai-xx** [kai-xx/laravel-rewrite-logger#1]
Symfony\Component\ErrorHandler\Error\FatalError: During inheritance of JsonSerializable: Uncaught Error: Call to undefined method xxx\Core\Providers\Log\Logger::channel() in /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Log/Logger.php:308
Stack trace:
#0 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(101): Illuminate\Log\Logger->__call('channel', Array)
#1 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(72): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecation('Return type of ...', '/var/www/html/c...', 61)
#2 /var/www/html/xxx-api/vendor/lcobucci/jwt/src/Claim/Basic.php(18): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Return type of ...', '/var/www/html/c...', 61)
#3 /var/www/html/xxx-api/vendor/composer/ClassLoader.php(571): include('/var/www/html/c...')
#4 /var/www/html/xxx-api/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/html/c...')
#5 /var/www/html/xxx-api/vendor/lcobucci/jwt/src/Claim/EqualsTo.php(19): Composer\Autoload\ClassLoader->loadClass('Lcobucci\\JWT\\Cl...')
#6 /var/www/html/xxx-api/vendor/composer/ClassLoader.php(571): include('/var/www/html/c...')
#7 /var/www/html/xxx-api/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/var/www/html/c...')
#8 /var/www/html/xxx-api/vendor/lcobucci/jwt/src/Claim/Factory.php(101): Composer\Autoload\ClassLoader->loadClass('Lcobucci\\JWT\\Cl...')
#9 [internal function]: Lcobucci\JWT\Claim\Factory->createEqualsTo('iss', 'http://127.0.0....')
#10 /var/www/html/xxx-api/vendor/lcobucci/jwt/src/Claim/Factory.php(59): call_user_func(Array, 'iss', 'http://127.0.0....')
#11 /var/www/html/xxx-api/vendor/lcobucci/jwt/src/Parser.php(133): Lcobucci\JWT\Claim\Factory->create('iss', 'http://127.0.0....')
#12 /var/www/html/xxx-api/vendor/lcobucci/jwt/src/Parser.php(61): Lcobucci\JWT\Parser->parseClaims('eyJpc3MiOiJodHR...')
#13 /var/www/html/xxx-api/vendor/tymon/jwt-auth/src/Providers/JWT/Lcobucci.php(131): Lcobucci\JWT\Parser->parse('eyJ0eXAiOiJKV1Q...')
#14 /var/www/html/xxx-api/vendor/tymon/jwt-auth/src/Manager.php(101): Tymon\JWTAuth\Providers\JWT\Lcobucci->decode('eyJ0eXAiOiJKV1Q...')
#15 /var/www/html/xxx-api/vendor/tymon/jwt-auth/src/JWT.php(200): Tymon\JWTAuth\Manager->decode(Object(Tymon\JWTAuth\Token))
#16 /var/www/html/xxx-api/vendor/tymon/jwt-auth/src/JWT.php(136): Tymon\JWTAuth\JWT->getPayload()
#17 /var/www/html/xxx-api/vendor/tymon/jwt-auth/src/JWT.php(149): Tymon\JWTAuth\JWT->checkOrFail()
#18 /var/www/html/xxx-api/vendor/tymon/jwt-auth/src/JWTGuard.php(79): Tymon\JWTAuth\JWT->check(true)
#19 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Auth/AuthManager.php(54): Tymon\JWTAuth\JWTGuard->user()
#20 [internal function]: Illuminate\Auth\AuthManager->Illuminate\Auth\{closure}(NULL)
#21 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Auth/AuthServiceProvider.php(97): call_user_func(Object(Closure), NULL)
#22 [internal function]: Illuminate\Auth\AuthServiceProvider->Illuminate\Auth\{closure}(NULL)
#23 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Http/Request.php(550): call_user_func(Object(Closure), NULL)
#24 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(170): Illuminate\Http\Request->user()
#25 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(63): Illuminate\Routing\Middleware\ThrottleRequests->resolveRequestSignature(Object(Illuminate\Http\Request))
#26 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '500', '1')
#27 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#30 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#31 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/html/xxx-api/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /var/www/html/xxx-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#49 /var/www/html/xxx-api/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#50 {main} in file /var/www/html/xxx-api/vendor/lcobucci/jwt/src/Claim/Basic.php on line 18

#0 {main}

**Comment by kai-xx** [comment]
fix
